name: browseros
repos:
  - name: browseros-main
    path: /Users/felarof01/Workspaces/build/browseros-main
  - name: browseros-workers
    path: /Users/felarof01/Workspaces/build/browseros-workers
  - name: browseros-ai-gateway
    path: /Users/felarof01/Workspaces/build/browseros-ai-gateway
engineers:
  - DaniAkash
  - felarof99
  - neel04
  - shadowfax92
  - shivammittal274
aliases:
  DaniAkash:
    - Dani Akash
  felarof99:
    - nithin.sonti
    - Felarof
  neel04:
    - neelgupta04
    - Neel Gupta
  shadowfax92:
    - nikhilsv92
    - Nikhil
    - Nikhil Sonti
  shivammittal274:
    - mittal.shivam103
