name: browseros
server_url: https://auctor-server.fly.dev
repos:
  - name: browseros-main
    path: /Users/felarof01/Workspaces/build/browseros-main
  - name: browseros-workers
    path: /Users/felarof01/Workspaces/build/browseros-workers
  - name: browseros-ai-gateway
    path: /Users/felarof01/Workspaces/build/browseros-ai-gateway
engineers:
  - DaniAkash
  - felarof99
  - neel04
  - shadowfax92
  - shivammittal274
