name: browseros
repos:
  - name: browseros-main
    path: /Users/felarof01/Workspaces/build/browseros-main
  - name: browseros-workers
    path: /Users/felarof01/Workspaces/build/browseros-workers
  - name: browseros-ai-gateway
    path: /Users/felarof01/Workspaces/build/browseros-ai-gateway
engineers:
  - nikhil
  - dani
  - shivam
  - neel
  - felarof01
aliases:
  nikhil:
    - shadowfax92
    - nikhilsv92
    - Nikhil
    - Nikhil Sonti
  dani:
    - DaniAkash
    - Dani Akash
  shivam:
    - shivammittal274
    - mittal.shivam103
  neel:
    - neel04
    - neelgupta04
    - Neel Gupta
  felarof01:
    - felarof99
    - nithin.sonti
    - Felarof
